import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';  

export default function Home() {
  const [socials, supports] = Links();

  return (
    <div className='h-full bg-slate-600'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <main className='h-full w-full p-2 pt-10 pb-24 space-y-8'>
        <div className='h-1/5 w-full flex flex-col space-y-8'>
          <div className='m-auto h-24 w-24 rounded-full hover:cursor-pointer'>
            <Link href='https://souzoumaker.com' passHref={true}>
              <Image className='rounded-full' src='/images/logo.webp' alt='souzoumaker logo' layout='responsive' width={100} height={100}/>
            </Link>
          </div>
          <div className='flex flex-col space-y-2'>
            <div className='m-auto text-base text-zinc-300'>@souzoumaker</div>
            <div className='m-auto w-2/3 md:w-1/3 text-base text-zinc-400 '>Welcome to my links page where you can find all the account and social media pages I run!</div>
          </div>
        </div>
        <div>
          <div className='flex pb-5 h-full font-semibold text-3xl text-slate-300'>
            <div className='m-auto w-auto'>
              Social Media
            </div>
          </div>
          <div className='h-full m-auto flex flex-col space-y-4'>
            {socials}
          </div>
        </div>
        <div>
          <div className='flex pb-5 h-full font-semibold text-3xl text-slate-300'>
            <div className='m-auto w-auto'>
              Support Me
            </div>
          </div>
          <div className='h-full m-auto flex flex-col space-y-4'>
            {supports}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://souzoumaker.com"
          target="_blank"
          rel="noopener noreferrer"
          className='text-slate-400'
        >
          Made by me using Next.js{' '}
          <span className={styles.logo}>
            <Image src='/images/logo-white.png' alt='souzoumaker icon' height={32} width={32}/>
          </span>
        </a>
      </footer>
    </div>
  )
}

function Links() {
  let socialLinks = [];
  let supportLinks = [];
  let sites = [
    { 
      name: 'Souzoumaker (Blog)',
      link: 'https://souzoumaker.com',
      type: 'social'
    },
    {
      name: 'Youtube',
      link: 'https://www.youtube.com/c/SouzouMaker',
      type: 'social'
    },
    {
      name: '3D Models',
      link: 'https://www.prusaprinters.org/social/42044-souzoumaker/prints',
      type: 'social'
    },
    {
      name: 'Instagram',
      link: 'https://www.instagram.com/souzoumaker/',
      type: 'social'
    },
    {
      name: 'Linkedin',
      link: 'https://www.linkedin.com/in/ealitt/',
      type: 'social'
    },
    {
      name: 'Etsy (Shop)',
      link: 'https://souzoumaker.etsy.com/',
      type: 'support'
    },
    {
      name: 'Patreon',
      link: 'https://patreon.com/souzoumaker',
      type: 'support'
    },
    {
      name: 'Paypal.me (Donate)',
      link: 'https://paypal.me/souzoumaker',
      type: 'support'
    },
    {
      name: 'Amazon Referral',
      link: 'https://amzn.to/3EFcQLn',
      type: 'support'
    },
  ]

  sites.forEach((site, index) => {
    if(site.type == 'social') {
      socialLinks.push(
        <Link href={site.link} passHref={true} key={index}>
            <button className='linkButton'>{site.name}</button>
        </Link>
        );
    }
    if(site.type == 'support') {
      supportLinks.push(
        <Link href={site.link} passHref={true} key={index}>
            <button className='linkButton'>{site.name}</button>
        </Link>
        );
    }
  })

  return [socialLinks, supportLinks];
}